### ISSUE TITLE
Example for Publish on PR has issue 

### ISSUE THREAD

**Issue by nicholascm** [expo/expo-github-action#109]
### Description of the bug
Example doesn't work

### To Reproduce
1. setup an expo repo
2. try to use example here: https://github.com/expo/expo-github-action#test-prs-and-publish-a-review-version
3. Note the error relating to "unsplash/comment-on-pr@main" when the github action runs

#### Expected behavior
Example should work as-is

#### Actual behavior
Failed Github Action
![image](https://user-images.githubusercontent.com/8185671/128618511-0303b361-833d-49bf-b8b5-0a5e51015285.png)

### Additional context
Simple fix.

**Comment by byCedric** [comment]
Thanks for the PR, I just merged it.
