### ISSUE TITLE
Discussion about docker image account

### ISSUE THREAD

**Issue by byCedric** [expo/expo-github-action#11]
### Topic and scope of discussion
Double checking if the docker account for the base-image (cached preinstalled Expo CLI image) is fine or needs to be changed.

### Motivation
Right now I've set up Travis CI to make a new image every week. It will create an image with both `:latest` and `:2` _(the major version of the CLI)_ tag, and push it to the registry for the Action. This will make sure that new updates of the CLI are included in the actions, without having to install it when running _every action_. 

Since I've set things up and don't know _if_ you guys have an Expo org or account to put it under, I used my own account (bycedric). I made it publicly visible in Travis so everyone can see that's the proper image. 

Is this something that we need to change, or just stick with this for now?

### Additional context
See issue #4 and PR #9.

**Comment by ide** [comment]
We use GCR for Docker images. It will take some set-up but I think the right thing to do is for us to create a public GCR bucket, create a GCP service account that only has write access to that bucket, and then add the credentials as secrets to CI that are unlocked only on `master`. This way writes are protected but if the service account credentials are compromised, the damage is very limited and it is easy to cycle credentials.

**Comment by byCedric** [comment]
If I can help with anything, feel free to spam-ping me!

**Comment by byCedric** [comment]
Just a heads up @nicknovitski, [the new version of Expo GitHub Action will remove the docker images](https://github.com/expo/expo-github-action/issues/18#issuecomment-530151402). For now, I moved them to another repository which makes this issue obsolete, I think.
