### ISSUE TITLE
EAS build on main branch throwing a dirty working tree error

### ISSUE THREAD

**Issue by cvburgess** [expo/expo-github-action#117]
### Description of the bug

```
eas build --platform ios --profile release --non-interactive --auto-submit
  shell: /usr/bin/bash -e {0}
  env:
    EXPO_TOKEN: ***

Warning! Your repository working tree is dirty.
This operation needs to be run on a clean working tree, please commit all your changes before proceeding.
    Error: Please commit all changes. Aborting...
Error: Process completed with exit code 1.
```

I am getting this error when following the docs. Any ideas on how this could be or how to fix it?

### To Reproduce
What steps did you perform which led to this issue?

```YAML
name: Expo Publish
on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-cache: true
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm install
      - run: expo publish
      - run: eas build --platform ios --profile release --non-interactive --auto-submit
```

#### Expected behavior
The build would succeed.

#### Actual behavior
The build failed with the above error.

### Additional context
See YAML.

**Comment by brentvatne** [comment]
can you add a step to your workflow to log the `git status` between `npm install` and `expo publish` and again between `expo publish` and ` eas build`?

**Comment by cvburgess** [comment]
npm install modified the package-lock, ill try using npm ci
```
Run git status
On branch production
Your branch is up to date with 'origin/production'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")```

**Comment by cvburgess** [comment]
Switching to `npm ci` appears to have fixed the issue... so I'm curious now how a library like https://www.npmjs.com/package/standard-version-expo is supposed to work with EAS?

Was planning on implementing that tomorrow but now I'm not sure how to use it in conjunction with this action.

**Comment by brentvatne** [comment]
@cvburgess - you would cut any new versions before running the build. if you want to do this on ci, then you would need ci to be able of making a commit, so possibly you have some action that cuts a new version and pushes a commit and then in response to that a build is kicked off

**Comment by cvburgess** [comment]
That's what I'm doing now, its just brittle with GitHub actions and protected branches: you need to use a personal token and when we did that we accidentally made a recursive set of commits that blew through our minutes for the month in ~15 minutes.

Its all working now but its an absolute pain for most dev teams with a small team unfamiliar with GHA (which I assume is a large part of the Expo userbase). Being able to pass this as a CLI arg would be amazing but I digress.

The "bug" here would be the way it shows up with two different version numbers in the EAS dashboard. If you do not support passing them the way I mentioned above, its very confusing to see that number appear in the builds list in EAS only to then see the build fail with an ominous message from apple upon submission. I would force both numbers in EAS to appear as the "true" build number to help people identify this a lot faster.

**Comment by brentvatne** [comment]
@cvburgess - can you elaborate on the last paragraph? i'd definitely like to avoid any situation where the dashboard provides incorrect information

**Comment by cvburgess** [comment]
Absolutely.

So we were using an ENV Var from github in our `app.config.js` - for examples sake, lets say that number is "123".

I think the code was like so: `buildNumber: process.env.RUN_NUMBER || "1"`

When it ran (successfully!) in GitHub Actions a new build with a build number of 123 would start in EAS.

When i'd hop over to EAS it would eventually fail, stating build number "1" had already been used.

So the UI of the build in EAS showed the "passed in" values from GHA but I guess EAS does an additional computation of the config files, got a different build number (1) and now I was looking at two build numbers for the same build.

The UI said 123 but the actual logs in the build echoed out 1.

Does that make sense?

I've added a screenshot of where the "incorrect" build number would appear for clarity.

![Screen Shot 2021-11-04 at 10 17 58](https://user-images.githubusercontent.com/2141199/140330265-2932a741-d3fa-41ce-9c8e-9762bbb1f949.png)

**Comment by brentvatne** [comment]
yup, that makes sense. we do indeed evaluate app.config.js locally when you run the build (in order to gather metadata) and again on the worker. so, if environment variables are different between those environments then the results may be inconsistent.

**Comment by cvburgess** [comment]
Would be wonderful to document that somewhere, a lot of EAS feels like a guessing game compared to the herculean effort to document Expo

**Comment by brentvatne** [comment]
it's documented here: https://docs.expo.dev/build/eas-json/#environment-variables
and here: https://docs.expo.dev/build-reference/variables/#environment-variables-and-appconfigjs

**Comment by naraB** [comment]
Hi @brentvatne,

is it possible to use the run_number of a github action as the build number? in other words: can I expose an environment variable to the eas submit worker?

**Comment by brentvatne** [comment]
write a script to set the build number in your app.json from the environment variable, then build with `--auto-submit`

**Comment by cvburgess** [comment]
Im doing what @brentvatne said above. Its annoying but it works.

Be careful with protected branches.
