### ISSUE TITLE
JavaScript heap out of memory error during expo publish

### ISSUE THREAD

**Issue by mgibeau** [expo/expo-github-action#12]
Basically, a duplicate of this issue: https://github.com/expo/expo-cli/issues/94.

The suggested fix through env variable applies and solves the issue, e.g.:
```
action "Publish" {
  uses = "expo/expo-github-action@2.3.0"
  env = {
    NODE_OPTIONS = "--max_old_space_size=4096"
  }
  args = "publish"
  secrets = ["EXPO_CLI_USERNAME", "EXPO_CLI_PASSWORD"]
}
```

According to the documentation the environments have up to 3.75 GB of ram: https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#runtime-environment-resources

Not sure how you would prefer to handle this, either through documentation or hardcoded within the Dockerfile?

**Comment by byCedric** [comment]
Hi @mgibeau! Thanks for reporting this with the detailed info. 😄 I think we should integrate it into the GitHub Action's docker image. Let's add a FAQ/Notes/Gotchas section in the read me to describe this. This way, if anyone wants to add custom `NODE_OPTIONS`, they can read about having to add this too.

I can make a PR later today! Again, thanks for this ❤️

**Comment by byCedric** [comment]
Again, thanks for mentioning this @mgibeau! I just drafted release `2.3.1` which includes your proposed fix. Hope it works without issues now! If it doesn't, feel free to open up other issues 😄

**Comment by mgibeau** [comment]
Awesome, thanks for the quick fix!

**Comment by bradbumbalough** [comment]
If anyone else comes here after encountering this issue, the fix above is no longer relevant. Now, you can simply apply the `NODE_OPTIONS` directly to the step like so:
```yml
- run: expo publish
  env:
    NODE_OPTIONS: --max_old_space_size=4096
```

**Comment by mouhamedaly** [comment]
> If anyone else comes here after encountering this issue using the latest version (`@v5`), the fix above is no longer relevant. Now, you can simply apply the `NODE_OPTIONS` directly to the step like so:
> 
> ```yaml
> - run: expo publish
>   env:
>     NODE_OPTIONS: --max_old_space_size=4096
> ```

I try this, but i have the same issue: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by tlmader** [comment]
Same issue here. Running with `NODE_OPTIONS: --max_old_space_size=4096` results in the same error.

**Comment by bradbumbalough** [comment]
Per this https://github.com/expo/expo-github-action/issues/58#issuecomment-681147148, can you try running it with `EXPO_DEV_SERVER=true` env var?

**Comment by mouhamedaly** [comment]
I tried EXPO_USE_DEV_SERVER=true and NODE_OPTIONS: --max_old_space_size=4096 but still having this issue. 

Expo 41

**Comment by melchoir55** [comment]
I'm also having this issue. It appeared after we upgraded from expo 3.x to 4.x
I've tried all the suggestions here including dev server and max space.

**Comment by melchoir55** [comment]
The reason I was having this problem is I initially erroneously applied `NODE_OPTIONS: --max_old_space_size=4096 ` to the expo image itself. It instead should be applied to the invocation. For example:

`- run: expo publish
  env:
    NODE_OPTIONS: --max_old_space_size=4096`

**Comment by helloint** [comment]
considering the Node.js [document](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes), should be --**max-old-space-size**=SIZE, but tested both `max_old_space_size` and `max-old-space-size` works.
