### ISSUE TITLE
Fails to install eas-cli (out of memory)

### ISSUE THREAD

**Issue by kennethlynne** [expo/expo-github-action#132]
### Description of the bug
Step ```Patching system watchers for the `ENOSPC` error``` seemingly fails without any feedback. Started failing the last day and has previously worked just fine.

### To Reproduce
Using expo/expo-github-action@v6 
![image](https://user-images.githubusercontent.com/390817/145572713-48e1ed53-fb7c-4473-a4ef-d26fd36e01fe.png)

#### Expected behavior
No fail. Allows build to continue

#### Actual behavior
Runs out of memory
```
Installing eas-cli (0.36.1) with yarn
  Skipping remote cache, not enabled...
  /usr/local/bin/yarn add eas-cli@0.36.1
  yarn add v1.22.17
  warning package.json: No license field
  warning No license field
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  [3/4] Linking dependencies...
  
  <--- Last few GCs --->
  
  [2019:0x4a2c6f0]    54370 ms: Scavenge 2025.0 (2053.1) -> 2023.2 (2053.1) MB, 6.8 / 0.0 ms  (average mu = 0.347, current mu = 0.353) allocation failure 
  [2019:0x4a2c6f0]    54396 ms: Scavenge 2025.6 (2053.1) -> 2024.3 (2053.1) MB, 6.9 / 0.0 ms  (average mu = 0.347, current mu = 0.353) allocation failure 
  [2019:0x4a2c6f0]    54417 ms: Scavenge 2027.0 (2061.1) -> 2025.5 (2061.1) MB, 13.9 / 0.0 ms  (average mu = 0.347, current mu = 0.353) allocation failure 
  
  
  <--- JS stacktrace --->
  
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xa389b0 node::Abort() [node]
   2: 0x96e0af node::FatalError(char const*, char const*) [node]
   3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
   4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
   5: 0xd73fd5  [node]
   6: 0xd74b5f  [node]
   7: 0xd8299b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
   8: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
   9: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
  10: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
  11: 0x1446379  [node]
Checking current authenticated account
  /opt/hostedtoolcache/expo-cli/4.13.0/x64/node_modules/.bin/expo whoami
  Error: Error: The process '/usr/local/bin/yarn' failed with exit code null
```

**Comment by kennethlynne** [comment]
Wait what, something else crashed before that! Updating description

**Comment by kennethlynne** [comment]
After more digging it turns out simply removing our yarn.lock file and installing yielded the same error message so it does not have anything to do with this project. Sorry for the noise!

**Comment by winstromming** [comment]
@kennethlynne Have just encountered this issue myself. Found that assigning `eas-version: latest` and `expo-version: latest` helped (and threw different errors), but ultimately upgrading the version of `node` to `16.x` on the machine running the action did the job.

See here: https://github.com/expo/expo-github-action/pull/22

<img width="499" alt="Screenshot 2021-12-13 at 09 55 42" src="https://user-images.githubusercontent.com/1196144/145782190-183e12da-87b2-42fa-b742-d99704f83139.png">

**Comment by kennethlynne** [comment]
Thanks for sharing @winstromming! We hit this again today. I highly prefer pinning dependencies to avoid rogue dependencies introducing stuff out of our control, making previous builds that succeeded suddenly fail without a single line of change in lockfiles or code 😭. We are also on node 14 tho. Will try latest, upgrade node and report back here

**Comment by kennethlynne** [comment]
Currently installing anything later than eas-cli@0.41.1 breaks with a out-of-memory issue locally and on github actions using Node 14.17 and Yarn 1.22.4

**Comment by kennethlynne** [comment]
We got the same problem with node@16.13.1 and eas-cli@0.43.0 (latest) :(

**Comment by kennethlynne** [comment]
Closed as it seems to only be related to eas-cli and not this repo. 
→ https://github.com/expo/eas-cli/issues/893

**Comment by tmhao2005** [comment]
I've just encountered the same issue then I tried to switch to `npm` as `packager: npm`, the problem appears to be sorted out for me :)

**Comment by kennethlynne** [comment]
It suddenly started working again for us again. 

However, we also upgraded to node 16.13.1 and added a resolution for @apollo/client in between

**Comment by tmhao2005** [comment]
Yes it worked for me with yarn again after I dropped the comment. Looks like something went wrong with yarn that period of time
