### ISSUE TITLE
QR Code and DeepLink not showed on Slack channel

### ISSUE THREAD

**Issue by francesco87** [expo/expo-github-action#184]
I'd like to send Expo QR Code project `{projectQR}` or A deep link to open the project in Expo Go `{projectDeepLink}` in a Slack channel, follow the example in this [page](https://github.com/expo/expo-github-action/tree/main/preview-comment#sending-preview-comments-elsewhere) .

Unfortunately QR Code is not showed in Slack the it shows the rest of message.
This is my GitHub Action:

name: Build and Preview for PR to develop

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 📦 Run Prettier, esLint and compile typescript file
        run: yarn lint

      - name: 📦 Run Test and
        run: yarn test

      - name: 🚀 Build app
        run: eas build --profile preview --platform all --non-interactive

      - name: 🚀 Publish on Expo's servers
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}

      - name: 💬 Comment in Slack
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: app-release
          slack-message: 'New deployment is ready! Preview: ${{ steps.preview.outputs.projectQR }}'

**Comment by byCedric** [comment]
The `💬 Comment preview` step doesn't have an ID, so the `steps.preview` has no value. It's simply not connected to the step containing the output variables.
