### ISSUE TITLE
Upgrade @action/core to remove deprecation warning of `set-output` command

### ISSUE THREAD

**Issue by lacasseio** [expo/expo-github-action#194]
### Description of the bug
[GitHub announced that `set-output` command is now deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This deprecation spam any CI build using Expo GitHub Actions with a deprecation message.

### To Reproduce
Use `expo/expo-github-action@v7` and/or `expo/expo-github-action/preview-comment@v7` in a GitHub workflow.

#### Expected behavior
There should be no deprecation warning appearing when using Expo actions.

#### Actual behavior
What did it actually result in?
We see deprecation warnings appearing when using Expo actions:
<img width="1380" alt="Screen Shot 2022-11-21 at 8 43 38 PM" src="https://user-images.githubusercontent.com/22181740/203144674-c903e21a-8d36-4a35-93b7-07ffa2764729.png">

### Additional context
It seems Expo GitHub Actions doesn't directly use `set-output` command but uses `setOutput` from `@action/core` library, which uses the deprecated `set-output` command. Luckily, [the issue was fixed (without API breakage) in version 1.10.0](https://github.com/actions/toolkit/pull/1178). Upgrading to that version should solve the issue. If the action is rebuilt, the `package.json` is correctly set up to pick the latest minor version. However, it would be safe to upgrade to 1.10.0 to make sure.

**Comment by byCedric** [comment]
Fixed by #202
