### ISSUE TITLE
workflow schema seems broken

### ISSUE THREAD

**Issue by Norfeldt** [expo/expo-github-action#213]
### Description of the bug

I have this extension installed which pulls the workflow schema to auto-completes

<img width="824" alt="Screenshot 2023-03-06 at 14 25 21" src="https://user-images.githubusercontent.com/678806/223124486-3baffe75-51c8-4c9d-9e34-9b9a38104c5b.png">

but it seems to be wrong

<img width="1321" alt="Screenshot 2023-03-06 at 14 25 37" src="https://user-images.githubusercontent.com/678806/223124490-c947233c-0f3e-40ca-a471-e3fadd14702d.png">

### To Reproduce

You need to have this expension installed

https://marketplace.visualstudio.com/items?itemName=cschleiden.vscode-github-actions

#### Expected behavior
a 1:1 with the auto-suggested (from workflow schema) and the actual allowed commands

#### Actual behavior
My CI fails

**Comment by byCedric** [comment]
Hi! I think the extension maintainers already fixed this. It seems like the autocomplete messed up the metadata from `expo/expo-github-action` and `expo/expo-github-action/preview`.

![image](https://user-images.githubusercontent.com/1203991/230092953-a0ee5b03-297f-4128-9378-c285e72adc87.png)

This doesn't happen for me with the extension version `v0.25.3`. Let me know if this isn't working for you!
