### ISSUE TITLE
EAS project not configured on Github Actions

### ISSUE THREAD

**Issue by henrymoulton** [expo/expo-github-action#217]
### Description of the bug
How would you shortly summarise the issue?

I saw this issue https://github.com/expo/eas-cli/issues/1426 which was closed but also noticed it was limited to CI environments, was wondering if you had any guesses @byCedric why this would happen?

**Comment by byCedric** [comment]
Hey @henrymoulton! The issue you are referring to is an error when you are missing the `expo.extra.eas.projectId` property in your app manifest. We moved away from owner + slug to identify projects, meaning that that field should be configured in your project.

If you have an open-source project, and don't like to add this ID to the project itself, you can use `eas init --id <UUID>` in CI ([see this example](https://github.com/byCedric/expo-monorepo-example/blob/main/.github/workflows/build.yml#L48))

If you have a closed-source project, you can grab the ID from [expo.dev](https://expo.dev) and put it in the app manifest. Either manually, or using `eas init --id <UUID>`.

Hope this helps!
