### ISSUE TITLE
You don't have the required permissions to perform this operation.

### ISSUE THREAD

**Issue by linonetwo** [expo/expo-github-action#228]
### Description of the bug

I already have repository secret

<img width="1287" alt="截屏2023-09-06 14 37 33" src="https://github.com/expo/expo-github-action/assets/3746270/f57ab02e-9337-4a03-9e6e-b09f4abcab01">

<img width="1322" alt="截屏2023-09-06 14 37 55" src="https://github.com/expo/expo-github-action/assets/3746270/a5440357-4345-4136-a7d1-db719349734d">

The run https://github.com/tiddly-gittly/TidGi-Mobile/actions/runs/6093556409/job/16533421643

### To Reproduce
What steps did you perform which led to this issue?

1. Create a repo in an Github Organization
2. Init with expo project
3. Setup repository secret and try run the workflow

#### Expected behavior

Run as local `eas build --platform android --non-interactive` does (logined)

#### Actual behavior

Error about "You don't have the required permissions to perform this operation."

### Additional context

Trying to use github actions to release an apk for a free opensource project in an organization. And I want to upload artifact to Github Release https://github.com/expo/expo-github-action/issues/182 so I don't need to pay for Google/Apple to upload to store, because it is a free opensourced project.

**Comment by linonetwo** [comment]
Fixed by:

1. create an organization on eas (previously it was on my personal eas account), now both eas and github use organization account,
1. connect github repo to the eas organization, then it works.

**Comment by Reinhartsamuel** [comment]
I encountered this problem when I cloned my repo to another Expo Project, with another Expo account of mine. 

To reproduce this, simply:

1. `eas whoami` --> make sure you already connected with the correct expo account on your repo before building.
2. If the account is not the same, `eas logout` and then `eas login` with the correct email and password
3. Last, connect the project id you get from expo dashboard by `eas init --id your-project-id-here`

**Comment by Ritheshnv** [comment]
> I encountered this problem when I cloned my repo to another Expo Project, with another Expo account of mine.
> 
> To reproduce this, simply:
> 
> 1. `eas whoami` --> make sure you already connected with the correct expo account on your repo before building.
> 2. If the account is not the same, `eas logout` and then `eas login` with the correct email and password
> 3. Last, connect the project id you get from expo dashboard by `eas init --id your-project-id-here`

Thank you so much....eas init --id <project id> accept overiding project it, should work now

**Comment by MohammedAlez** [comment]
Try to delete the projectId in your app.json because it's related to another account

**Comment by Ritheshnv** [comment]
Yes, thanks it worked
