### ISSUE TITLE
Github action fails to start because author is not verified in the GitHub Marketplace

### ISSUE THREAD

**Issue by ddavydov** [expo/expo-github-action#237]
expo/expo-github-action@v8 and expo/expo-github-action/preview@v8 are not allowed to be used. Actions in this workflow must be: within a repository owned by organization, created by GitHub, or **verified in the GitHub Marketplace**.

As a workaround I can fork the repo to my organization, but it would nice if expo can be verified in the GitHub Marketplace

**Comment by byCedric** [comment]
I can happily say that talks are underway to get this done. Unfortunately, it requires multiple verifications and even a technical partnership agreement to get it done.

**Comment by byCedric** [comment]
Well, happy to announce 😄 
![image](https://github.com/expo/expo-github-action/assets/1203991/fe49f709-175c-489e-94d8-084059f2d013)
