### ISSUE TITLE
QR codes broken when using custom schemes

### ISSUE THREAD

**Issue by erickreutz** [expo/expo-github-action#240]
Firstly `app.json` defines the type of `scheme` as `string | string[]` and from what I can tell this action doesn't account for an array.
https://github.com/expo/expo-github-action/blob/57dcabe749340c8c995ee0334cd7c547c35770d0/src/actions/preview.ts#L113

I've also noticed that QR codes break when using custom schemes that deviate from the default project `slug`. For example if the scheme in my `app.json` is `myapp-dev`  and the slug is `myapp` and the `bundleId` is `com.org.myapp` then `expo prebuild` will add the following schemes to `Info.plist`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    ...
    <array>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>myapp-dev</string>
          <string>com.org.myapp</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>exp+myapp</string>
        </array>
      </dict>
    </array>
    ...
  </dict>
</plist>
```

You'll then use the custom scheme to get a QR code here
```
https://qr.expo.dev/eas-update?appScheme=myapp-devprojectId=123&groupId=456
```
This returns a QR code that the expo-dev-client will not understand because it appends `exp+` to all app schemes and `exp+myapp-dev` is not a known scheme.

You can see an example of this problem at https://expo.dev

![image](https://github.com/expo/expo-github-action/assets/59875/afa06cb7-1bed-445d-83a3-b56d84208d64)

It says "use appScheme" from app.json but it's not the `appScheme` it's expecting - it's the project slug because the appScheme (if it's user-defined) won't work with the `exp+` prefix.

**Comment by byCedric** [comment]
Hi @erickreutz, thanks for reporting this issue! I've just patched support for multiple app schemes, this was added lately and wasn't updated in this action yet. See PR #244 for this.

The other issue, related to the QR code prefixing schemes with `exp+`, work is on it's way. But, since this is part of our internal services, it's on a private repo.

Will provide an update once I have more!

**Comment by byCedric** [comment]
The multi-scheme fix, and an optional "overwrite" `app-scheme` input property are released on `expo/expo-github-action/preview@v8`.

The QR code with `exp+` prefix will likely take a bit longer because of a US holiday.

**Comment by erickreutz** [comment]
@byCedric thank you!
