### ISSUE TITLE
continuous-deploy-fingerprint action does not work

### ISSUE THREAD

**Issue by elliotmjackson** [expo/expo-github-action#272]
### Description of the Bug
The GitHub Action `continuous-deploy-fingerprint` from Expo fails during the `eas whoami` command, which i assume is used to validate the authenticated Expo account. I thought this might be my EXPO_TOKEN but I was able to validate this with another job. 

### To Reproduce
1. Set up the `continuous-deploy-fingerprint` GitHub Action in a workflow.
2. Configure necessary inputs like `profile`, `branch`, and Expo tokens.
3. Execute the workflow in a scenario that triggers the action (e.g., push event).
4. Observe the failure in the step where `eas whoami` is executed.

#### Expected Behavior
The expected outcome was for the `eas-cli` to authenticate successfully, allowing the GitHub Action to complete its tasks, including checking current project fingerprints, initiating EAS builds, and publishing updates.

#### Actual Behavior
The action fails during the authentication check with the error "GraphQL request failed", leading to a workflow termination with exit code 1.

**Comment by elliotmjackson** [comment]
@wschurman @Kudo please advise

**Comment by wschurman** [comment]
@elliotmjackson - Thanks for the report. This action is still in very early stages of development so it's not yet ready for use. That being said, I'll try to repro and will fix before release and announcement.

**Comment by elliotmjackson** [comment]
Hot off the press then, cheers.
