### ISSUE TITLE
Continuous deploy fails to update

### ISSUE THREAD

**Issue by cmaycumber** [expo/expo-github-action#285]
### Description of the bug
Continuous deploy GitHub action doesn't seem to be working as expected.

### To Reproduce

1. Start GitHub action

#### Expected behavior
Deploys update/build properly

#### Actual behavior
Throws error:
```
Could not create a new EAS Update: Error: The process '/opt/hostedtoolcache/eas-cli/9.0.7/x64/node_modules/.bin/eas' failed with exit code 1
```

### Additional context
![Screenshot 2024-05-17 at 12 32 14 PM](https://github.com/expo/expo-github-action/assets/36460656/c96fb229-a510-41d8-89f2-20986d39b2c3)

**Comment by vargajacint** [comment]
Same in here, here is the debug logs:

```bash
/opt/hostedtoolcache/node/18.20.2/x64/bin/npx expo-updates fingerprint:generate --platform android --debug
/home/runner/work/zabit-mono/zabit-mono/node_modules/expo-updates/build-cli/cli.js:46
command]().then((exec) => exec(commandArgs));
                 ^

TypeError: commands[command] is not a function
    at Object.<anonymous> (/home/runner/work/zabit-mono/zabit-mono/node_modules/expo-updates/build-cli/cli.js:46:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:1[77](https://github.com/Intentional-Digital/zabit-mono/actions/runs/9250929899/job/25445487532#step:6:78):18)
    at Object.<anonymous> (/home/runner/work/zabit-mono/zabit-mono/node_modules/expo-updates/bin/cli.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
```

**Comment by CamBowes** [comment]
@Kudo @wschurman Can you take a look at this please? I'm having issues with this too as i'm trying to setup CD for my new app.

At first i thought it may be because it's a new app and i haven't run eas yet but i ran it and it still doesn't work

**Run Output**
<img width="1324" alt="Screenshot 2024-06-10 at 15 57 12" src="https://github.com/expo/expo-github-action/assets/102999681/b929ba5e-2f23-41ae-8e10-e3bc60620f4f">

**My Flow:**
<img width="905" alt="Screenshot 2024-06-10 at 15 56 51" src="https://github.com/expo/expo-github-action/assets/102999681/18de8f5e-25b0-4541-a921-d5334c6aa5aa">

**Comment by Kudo** [comment]
hi there! could you try to re-run the failed github action job and enable the [debug log](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging). it will show more errors.

**Comment by cmaycumber** [comment]
Yeah I'll test this out and post back here!

**Comment by tharakadesilva** [comment]
Got the same error, enabled debug logs and ran into:

> Generating a new Keystore is not supported in --non-interactive mode
>    Error: build command failed.

Followed the steps in https://github.com/expo/eas-cli/issues/476 (ran it locally interactively) and it's now sorted. Have to do it for both platforms.

**Comment by wschurman** [comment]
Documentation for this action has been updated to detail that an initial run of the build needs to be done manually to generate credentials ahead of use of this action. Thanks for the report!
