### ISSUE TITLE
When expo build:android completes is it possible to access the apk url? 

### ISSUE THREAD

**Issue by shopcam** [expo/expo-github-action#41]
Everything is working great. However, I want to have my apk automatically push into [Firebase App Distribution](https://github.com/marketplace/actions/firebase-app-distribution) once the build completes.

The output log displays something like this when `expo build:android` finishes. 

✔ Build finished.
[00:37:25] Successfully built standalone app: https://expo.io/artifacts/8e3de24e-aaaa-bbbb-cccc-d93kfksadkfksda

How would I go about grabbing that URL during the process? Is it possible?

**Comment by byCedric** [comment]
Hi @shopcam, sorry for my late reply! You can do this with the Expo CLI, there are two options:

1. Add a webhook that's called when the standalone build is finished
2. Run `expo upload:android` or `expo upload:ios` to upload after waiting on a successful build

Option 1 requires you to have a simple webserver running that takes care of handling the request. You can [read more about it here](https://docs.expo.io/distribution/building-standalone-apps/#4-wait-for-it-to-finish-building).

Option 2 doesn't require a webserver, but it does have some caveats. It only works on MacOS for example (which is also supported in GH actions). For this, you can [read more here](https://docs.expo.io/distribution/uploading-apps/).

Hope it helps!

**Comment by shopcam** [comment]
Great, thank you @byCedric. I'll give this a shot.

**Comment by tspvivek** [comment]
@byCedric Github action is a great addon for expo. Build and publish works fine. But is it possible in action to configure "expo upload:ios" to use FASTLANE_SESSION or use app specific password to upload without asking 2FA code. Thanks.
