### ISSUE TITLE
How do I get my expo-token?

### ISSUE THREAD

**Issue by jakemwood** [expo/expo-github-action#60]
### Topic and scope of discussion
In the README, there is a point of:

```
expo-token is available from Expo CLI 3.25.0.
```

I am using Expo-cli 3.27.7...

```
% expo --version
3.27.7
```

However, I can find no information about a token anywhere. How do I get my hands on my Expo token so I can use it in my CI workflow?

### Motivation
Why should we have this discussion?

I agree with the README that using a token is a better way to integrate with a CI/CD pipeline (like GitHub Actions) than a username and password. However, Expo docs themselves have very little information in the way of getting your hands on the token. If this feature is to be used, complete documentation needs to be available.

### Additional context
Can you further explain the purpose of this discussion? E.g., screenshots or real-world examples.

**Comment by jakemwood** [comment]
Sorry -- just saw the comment here! https://github.com/expo/expo-github-action/pull/57#issuecomment-692581333

**Comment by friederbluemle** [comment]
For future visitors, this is where you generate your expo token:

https://expo.dev/settings/access-tokens
