### ISSUE TITLE
Warning: The `add-path` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo-github-action#66]
#### Old version
What did you find that should be changed?
When running this command the logs emit:

> Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

#### New version
How should it look after the suggested change?
Likely this is a required fix at some point, it looks as though it allows printing secure variables. 

### Additional context
Can you further clarify the change? E.g., link to a dictionary or real-world examples.

This link seems to show how to do env injection without `add-path`
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by byCedric** [comment]
Hi @jonathanstiansen, thanks for the report! And sorry for the delay. From the changelog link you mentioned, I see that they have updated the `@actions/core` methods to use this newer and more secure method starting from version `1.2.6`.

> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated `addPath` and `exportVariable` functions.

This is the one that's currently used, so I'm not 100% why you are seeing this or what we can do to fix it. Do you have an example repo for this? Or do you use self-hosted GH runners, which might not be upgraded yet?

**Comment by byCedric** [comment]
Again, sorry for the delay! Could you try the latest version (`v5` or `5.3.1`)? This should include the version bump to of `@actions/core` to `1.2.6`, and fix this issue! If not, please let me know and I'll dig in!
