### ISSUE TITLE
Request: Release new version with recent cache updates

### ISSUE THREAD

**Issue by mondash** [expo/expo-github-action#75]
#### Old version
The latest updates using the official cache action are only available in the master branch

#### New version
I should be able to use this action (with the recent updates to caching) with a specific tag instead instead of using the master.

**Comment by byCedric** [comment]
There is an update coming with improved error handling, I'm testing that and will release a new version! (probably v6)

**Comment by byCedric** [comment]
Done, `5.4.0` is out! Thanks for your help with upgrading the cache @mondash ❤️
